### ISSUE TITLE
Problem with accessWidener

### ISSUE THREAD

**Issue by Boobies** [WearBlackAllDay/DimensionalThreading#30]
Crash with only DimensionalThreading loaded:

```
[02:42:51] [main/INFO]: Loading for game Minecraft 1.17
[02:42:51] [main/INFO]: [FabricLoader] Loading 4 mods:
	- dimthread@1.2.5
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod dimthread
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:432)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:135)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:430)
	... 10 more
Exiting with -1
Process exited with code 255.
```

**Comment by WearBlackAllDay** [comment]
you forgot to add the fabric api 
https://github.com/FabricMC/fabric/releases

**Comment by Boobies** [comment]
I actually didn't. I tried with and without the API and when it still crashed I assumed the mod didn't even care.

**Comment by Boobies** [comment]
I only removed Fabric API because I thought it wasn't needed as I get the same error with Fabric API:

```
[22:45:56] [main/INFO]: Loading for game Minecraft 1.17
[22:45:56] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[22:46:00] [main/INFO]: [FabricLoader] Loading 48 mods:
	- dimthread@1.2.5
	- fabric@0.36.0+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d03d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b44633d
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.9+a722d8c03d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab61213d
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afa3d
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+155f865c3d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.11+e36969833d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod dimthread
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:432)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:135)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:430)
	... 10 more
Process exited with code 255.
```

Please reopen.

**Comment by WearBlackAllDay** [comment]
it appears you have donwloaded the wrong jar file then. 
Be sure to use `DimThread-1.2.5.jar`, not -dev, not -sources

**Comment by Boobies** [comment]
Yes, that is the one I got. Unfortunately, I do not have access to that setup any longer because my drive broke down. I'm only speculating at this point but it could be that because my drive was failing, the file somehow became corrupt.
