### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MAX-XiaoKui** [WearBlackAllDay/DimensionalThreading#38]
log: 
````py
[17:02:49] [Server thread/INFO]: POEG_py has the following entity data: [-84.1849802415203d, 63.0d, 515.7075345211305d]
[17:02:49] [Server thread/INFO]: POEG_py has the following entity data: "minecraft:overworld"
[17:02:49] [Server thread/INFO]: ChengXi123 has the following entity data: [20.03080146584874d, 15.0d, 408.1845403782194d]
[17:02:49] [Server thread/INFO]: ChengXi123 has the following entity data: "minecraft:overworld"
[17:02:50] [Server thread/INFO]: MAX_XiaoKui has the following entity data: [16.087132866766098d, 21.0d, 372.1741317173482d]
[17:02:50] [Server thread/INFO]: MAX_XiaoKui has the following entity data: "minecraft:overworld"
[17:02:50] [Server thread/INFO]: Comet3721 has the following entity data: [193.61884473198836d, 1.0d, 0.6082258874926021d]
[17:02:50] [Server thread/INFO]: Comet3721 has the following entity data: "minecraft:the_end"
[17:02:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[%5B%E4%BC%98%E5%8C%96-%E4%B8%96%E7%95%8C%E5%A4%9A%E7%BA%BF%E7%A8%8B%5D%20DimThread-1.2.5.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zpc000$tickWorlds(MixinMinecraftServer.java:4330) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MixinMinecraftServer.java:880) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(MixinMinecraftDedicatedServer.java:335) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MixinMinecraftServer.java:831) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bkb000$modifiedRunLoop(MixinMinecraftServer.java:7890) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MixinMinecraftServer.java:676) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MixinMinecraftServer.java:270) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5800/0x00000000339fc398.run(Unknown Source) [intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668) ~[intermediary-server.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:950) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_18727(MixinThreadedAnvilChunkStorage.java:1024) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_14161(MixinServerChunkManager.java:385) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_12127(MixinServerChunkManager.java:324) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(MixinServerWorld.java:372) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.md46216a$lambda$tickWorlds$0$2(MixinMinecraftServer.java:4320) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$7285/0x0000000094ef9548.run(Unknown Source) ~[?:?]
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34) ~[%5B%E4%BC%98%E5%8C%96-%E4%B8%96%E7%95%8C%E5%A4%9A%E7%BA%BF%E7%A8%8B%5D%20DimThread-1.2.5.jar:?]
	at net.minecraft.server.MinecraftServer.md46216a$lambda$tickWorlds$1$1(MixinMinecraftServer.java:4318) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$7280/0x0000000094eec910.accept(Unknown Source) ~[?:?]
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[d83bcb3a-0701-4690-b5fe-7cb68e4e1498.jar:?]
	at wearblackallday.util.ThreadPool$$Lambda$7282/0x0000000094eece40.run(Unknown Source) ~[?:?]
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[d83bcb3a-0701-4690-b5fe-7cb68e4e1498.jar:?]
	at wearblackallday.util.ThreadPool$$Lambda$7283/0x0000000094eefe60.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	... 1 more
[17:02:56] [Server thread/ERROR]: This crash report has been saved to: /opt/skimit-fabric-survival/server/./crash-reports/crash-2021-07-30_17.02.56-server.txt
````
crash-report: 
````sql
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021/7/30 下午5:02
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:950)
	at net.minecraft.class_3898.method_18727(MixinThreadedAnvilChunkStorage.java:1024)
	at net.minecraft.class_3215.method_14161(MixinServerChunkManager.java:385)
	at net.minecraft.class_3215.method_12127(MixinServerChunkManager.java:324)
	at net.minecraft.class_3218.method_18765(MixinServerWorld.java:372)
	at net.minecraft.server.MinecraftServer.md46216a$lambda$tickWorlds$0$2(MixinMinecraftServer.java:4320)
	at net.minecraft.server.MinecraftServer$$Lambda$7285/0x0000000094ef9548.run(Unknown Source)
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)
	at net.minecraft.server.MinecraftServer.md46216a$lambda$tickWorlds$1$1(MixinMinecraftServer.java:4318)
	at net.minecraft.server.MinecraftServer$$Lambda$7280/0x0000000094eec910.accept(Unknown Source)
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49)
	at wearblackallday.util.ThreadPool$$Lambda$7282/0x0000000094eece40.run(Unknown Source)
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at wearblackallday.util.ThreadPool$$Lambda$7283/0x0000000094eefe60.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:950)
	at net.minecraft.class_3898.method_18727(MixinThreadedAnvilChunkStorage.java:1024)
	at net.minecraft.class_3215.method_14161(MixinServerChunkManager.java:385)
	at net.minecraft.class_3215.method_12127(MixinServerChunkManager.java:324)
	at net.minecraft.class_3218.method_18765(MixinServerWorld.java:372)
	at net.minecraft.server.MinecraftServer.md46216a$lambda$tickWorlds$0$2(MixinMinecraftServer.java:4320)
	at net.minecraft.server.MinecraftServer$$Lambda$7285/0x0000000094ef9548.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Comet3721'/40780, l='ServerLevel[world]', x=193.62, y=1.00, z=0.61]]
	Chunk stats: 2025
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-43,63,239), Section: (at 5,15,15 in -3,3,14; chunk contains blocks -48,0,224 to -33,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1061557822 game time, 1265262041 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 161717 (now: false), thunder time: 126669 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:11)
	at net.minecraft.server.MinecraftServer.handler$zpc000$tickWorlds(MixinMinecraftServer.java:4330)
	at net.minecraft.server.MinecraftServer.method_3813(MixinMinecraftServer.java:880)
	at net.minecraft.class_3176.method_3813(MixinMinecraftDedicatedServer.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MixinMinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$bkb000$modifiedRunLoop(MixinMinecraftServer.java:7890)
	at net.minecraft.server.MinecraftServer.method_29741(MixinMinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MixinMinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$5800/0x00000000339fc398.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.19.0-17-amd64
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9), Eclipse OpenJ9
	Memory: 10735293592 bytes (10237 MiB) / 15435038720 bytes (14720 MiB) up to 16642998272 bytes (15872 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: SVGA II Adapter
	Graphics card #0 vendor: VMware (0x15ad)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x0405
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12974.77
	Virtual memory used (MB): 19602.50
	Swap memory total (MB): 6144.99
	Swap memory used (MB): 3816.81
	JVM Flags: 11 total; -Xoptionsfile=/usr/lib/jvm/adoptopenjdk-16-openj9-jre-amd64/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xmx15872M -Xms14336M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bluemap: BlueMap 1.5.5
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.2.0
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.33
		cloud-v1: Cloud 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-brigadier: cloud-brigadier 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-core: cloud-core 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-services: cloud-services 1.5.0-SNAPSHOT
		com_github_wearblackallday_javautils: JavaUtils 1b369d41cd
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		dimthread: DimensionalThreading 1.2.5
		dynmap: Dynmap 3.2-beta-2
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fabricproxy-lite: FabricProxy Lite 1.1.5
		fastfurnace: FastFurnace 1.17-3.0
		fzbbl: FZ's Bedrock Breaked List 1.17-1.2.0
		hydrogen: Hydrogen 0.3
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: Eclipse OpenJ9 VM 16
		krypton: Krypton 0.1.4
		ledger: Ledger 1.0.2
		lithium: Lithium 0.7.3
		luckperms: LuckPerms 5.3.53
		minecraft: Minecraft 1.17.1
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.8.0
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.8.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		server_translations_api: Server Translations API 1.4.5+1.17
		skinrestorer: Skin Restorer 1.0.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		spark: spark 1.6.1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		tabtps-fabric: TabTPS 1.3.8
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
	Loaded Scarpet Apps: 
		here
		tagplayer
	Player Count: 5 / 32; [EntityPlayerMPFake['Bot'/13398, l='ServerLevel[world]', x=-33.31, y=63.75, z=319.50], class_3222['ChengXi123'/121625, l='ServerLevel[world]', x=7.73, y=16.20, z=387.39], class_3222['Comet3721'/40780, l='ServerLevel[world]', x=193.62, y=1.00, z=0.61], class_3222['MAX_XiaoKui'/31519, l='ServerLevel[world]', x=16.48, y=19.00, z=372.49], class_3222['POEG_py'/142299, l='ServerLevel[world]', x=-85.03, y=114.19, z=522.33]]
	Data Packs: vanilla (incompatible), file/bukkit (incompatible), Fabric Mods, file/FZ-sDatapack-2.1.0-去除网络用语
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
````

**Comment by WearBlackAllDay** [comment]
one of the numerous mods is causing an incomompatibility. I need to know which one to be potentially able to do anything.

**Comment by MAX-XiaoKui** [comment]
Eh, I can't reproduce. It crashed only one time.

**Comment by red2blue** [comment]
possibly c2me. mine crashed with dimthread when I had c2me on as well
