### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by ghost** [WearBlackAllDay/DimensionalThreading#66]
[16:52:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[DimThread-1.2.7.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cgj000$tickWorlds(MinecraftServer:9320) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zhb000$modifiedRunLoop(MinecraftServer:4380) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
	at com.natamus.stackrefill.events.RefillEvent.onWorldTick(RefillEvent.java:99) ~[stackrefill-fabric_1.19.x-2.2.jar:?]
	at com.natamus.stackrefill.Main.lambda$registerEvents$0(Main.java:31) ~[stackrefill-fabric_1.19.x-2.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84) ~[fabric-lifecycle-events-v1-2.1.0+33fbc738a9-c697e79f4c4115d8.jar:?]
	at net.minecraft.server.world.ServerWorld.handler$cmm000$startWorldTick(ServerWorld:17223) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:279) ~[?:?]
	at net.minecraft.server.MinecraftServer.mdf5d926$lambda$tickWorlds$0$5(MinecraftServer:9310) ~[server-intermediary.jar:?]
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34) ~[DimThread-1.2.7.jar:?]
	at net.minecraft.server.MinecraftServer.mdf5d926$lambda$tickWorlds$1$4(MinecraftServer:9308) ~[server-intermediary.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more

I think this issue comes from this mod:
https://www.curseforge.com/minecraft/mc-mods/stack-refill-fabric

Thanks already:)

**Comment by ghost** [comment]
I was updating my modpack and everything works now - not related with Stack Refill.
