### ISSUE TITLE
Crash server join on 1.19.2

### ISSUE THREAD

**Issue by ghost** [WearBlackAllDay/DimensionalThreading#70]
net.minecraft.class_148: Ticking entity
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[DimThread-1.2.7.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cfo000$tickWorlds(MinecraftServer:7825) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zih000$modifiedRunLoop(MinecraftServer:3885) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at net.minecraft.server.network.ServerPlayerEntity.handler$ejd000$wju$tickLogic(ServerPlayerEntity:23259) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:482) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:712) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:466) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:371) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:339) ~[?:?]
	at net.minecraft.server.MinecraftServer.md175303$lambda$tickWorlds$0$4(MinecraftServer:7815) ~[server-intermediary.jar:?]
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34) ~[DimThread-1.2.7.jar:?]
	at net.minecraft.server.MinecraftServer.md175303$lambda$tickWorlds$1$3(MinecraftServer:7813) ~[server-intermediary.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.handler$ejd000$wju$tickLogic(ServerPlayerEntity:23259) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:482) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:712) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:466) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:371) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:339) ~[?:?]
	at net.minecraft.server.MinecraftServer.md175303$lambda$tickWorlds$0$4(MinecraftServer:7815) ~[server-intermediary.jar:?]
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34) ~[DimThread-1.2.7.jar:?]
	at net.minecraft.server.MinecraftServer.md175303$lambda$tickWorlds$1$3(MinecraftServer:7813) ~[server-intermediary.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[com_github_wearblackallday_javau-bd58640372-35ccf0e183c6d6cd.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more

**Comment by ghost** [comment]
Crash came from Wall Jump Mod.
