### ISSUE TITLE
Gravity duping is removed. 

### ISSUE THREAD

**Issue by ZuccySuccy** [WearBlackAllDay/DimensionalThreading#9]
Not sure if it works with the 4 gravity block types or all dupers, but I know that it is fixed with a ray style duper. The blocks on the overworld side stay as expected, but the gravity entity on the end side is not there which is the expected behavior

**Comment by DragonEggBedrockBreaking** [comment]
Bug confirmed with dragon egg duper, someone's efficient rewiring of ilmango's design I found on discord.

**Comment by Apricityx** [comment]
This feature usually useful for some redstone used server

**Comment by coke-the-gal** [comment]
Issue is caused by EntityMixin.java, when removed sand duping works as in vanilla.

**Comment by Apricityx** [comment]
> Issue is caused by EntityMixin.java, when removed sand duping works as in vanilla.

So I can fix it by just delete EntityMixin.java?

**Comment by coke-the-gal** [comment]
Ehh, no. Removing the file fixes it in singleplayer worlds, but on servers, when you activate the duper, it causes a server crash. Would have put this in originally, but I couldnt test it on a server until yesterday.

**Comment by Apricityx** [comment]
> Ehh, no. Removing the file fixes it in singleplayer worlds, but on servers, when you activate the duper, it causes a server crash. Would have put this in originally, but I couldnt test it on a server until yesterday.

Then how can i fix it on my server?

**Comment by coke-the-gal** [comment]
No clue, just documenting my attempts

**Comment by Apricityx** [comment]
Fine,thank you

**Comment by Syntax3rror404** [comment]
Get a crash with you fix:

```
net.minecraft.class_148: Exception ticking world
        at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[DimThread-1.2.6-sand-duper-fix.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zim000$tickWorlds(MinecraftServer.java:4336) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:896) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2896) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException
[19:29:48] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-03-15_19.29.48-server.txt
[19:29:48] [Server thread/INFO]: Stopping server
```

**Comment by xiaoyu2006** [comment]
> Get a crash with your fix:
> 
> ```
> net.minecraft.class_148: Exception ticking world
>         at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[DimThread-1.2.6-sand-duper-fix.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$zim000$tickWorlds(MinecraftServer.java:4336) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:896) ~[server-intermediary.jar:?]
>         at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2896) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ClassCastException
> [19:29:48] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-03-15_19.29.48-server.txt
> [19:29:48] [Server thread/INFO]: Stopping server
> ```

@Syntax3rror404 No idea why this crashed. It works on both my local test environment and @Apricityx ‘s server.

**Comment by Syntax3rror404** [comment]
It runs on mc 1.18.2 with latest fabric and fabric api only with the mods carpet, litihum, phosphor and voicechat. It have 4 GB RAM and 12 CPU Cores. Without the dimthread mod it runns fine but with players in end, nether, overworld the mspt gots near 40 with your mod we have 17

**Comment by xiaoyu2006** [comment]
@Syntax3rror404 I have bumped dependency versions here:  https://github.com/MCTown/DimensionalThreading/releases/download/v1.2.6-sand-duper-fix/DimThread-1.2.6-1.18.2-sand-duper-fix.jar . I don’t know if it will work.

Note that the fix still have some known bugs about dragon eggs. Don’t rely on it.

BTW you have way too much CPUs and too little RAM.

**Comment by xiaoyu2006** [comment]
> @xiaoyu2006 While your fix does solve part of the problem, it still isn't exactly vanilla behavior, below I've attached 2 videos The first one showing the dupe running in vanilla, and the other running w/ your fix.
> 
> Without:
> 
>  javaw_6fVArPvEWj.mp4 
> 
> With:
> 
>  javaw_rpVMedUPLe.mp4

@LarveyOfficial Please provide an game archive for further debugging.

**Comment by LarveyOfficial** [comment]
> > @xiaoyu2006 While your fix does solve part of the problem, it still isn't exactly vanilla behavior, below I've attached 2 videos The first one showing the dupe running in vanilla, and the other running w/ your fix.
> > Without:
> > javaw_6fVArPvEWj.mp4
> > With:
> > javaw_rpVMedUPLe.mp4
> 
> @LarveyOfficial Please provide an game archive for further debugging.

@xiaoyu2006 Here is a google drive with the server I was using to test.
https://drive.google.com/file/d/1AUqoEQqRB9fuRttlGEgcoKIO8ZxqrSty/view?usp=sharing
Strong hold at ``/execute in minecraft:overworld run tp @s 1544.13 -25.76 -595.81 75.59 13.66``

**Comment by xiaoyu2006** [comment]
@LarveyOfficial Sure. I’ll take a look when I have time.

**Comment by LarveyOfficial** [comment]
@xiaoyu2006 Any updates?

**Comment by xiaoyu2006** [comment]
@LarveyOfficial There’s a more elegant hack in commit https://github.com/MCTown/DimensionalThreading/commit/a912fcf0c96ef37b2ec07ce78996d8571a62c6ab, however it will create a lot of spam messages in server console. (I have no more time to debug it. My time is very limited.)

Download the fix [here](https://github.com/MCTown/DimensionalThreading/actions/runs/2198775736). I will release it when I have more time to fix the spammed console.

**Comment by xiaoyu2006** [comment]
Update: Should work fine https://github.com/MCTown/DimensionalThreading/commit/12eae97a486f0a56f56dfcecbb5ce0105b6bed4b this time.

Grab the jar [here](https://github.com/MCTown/DimensionalThreading/actions/runs/2212484280). I will release it when everything is fine.

**Comment by micrwvae** [comment]
any updates to this

**Comment by LarveyOfficial** [comment]
Not that I've heard of no
